"""add Problem.statement

Revision ID: 4acff439f3e9
Revises: c1c2994e799e
Create Date: 2023-05-24 16:52:29.475746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acff439f3e9'
down_revision = 'c1c2994e799e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statement', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('statement')

    # ### end Alembic commands ###
