"""alter primary key of ContestSubmission

Revision ID: da48dedbcf80
Revises: c511096df254
Create Date: 2023-05-26 22:19:50.752679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da48dedbcf80'
down_revision = 'c511096df254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_submission',
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id', 'idx'], ['contest_problem.contest_id', 'contest_problem.idx'], ),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contest_submission')
    # ### end Alembic commands ###
